openapi: 3.0.0
info:
  version: 1.0.0
  title: tSNS API
  description: "**tiny-SNS API** is a backend providing basic instagram alike functionalities such as registering, following, posting, commenting and expressing how one feels about posts and comments"
  contact:
    name: Jiwoo Jeon
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /api/auth/register:
    post:
      summary: register new users
      tags:
        - Auth
      description: register new users
      requestBody:
        description: "password must contain least one special char, lower and upper char, and a number"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/register"
            example:
              nickname: user1
              email: example@gmail.com
              password: UPlow123!
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/registerRes"
              example:
                _id: a1froas2314adf
                nickname: user1
        "400":
          description: "Bad Request, reason in body"

  /api/auth/login:
    post:
      summary: login users
      tags:
        - Auth
      description: login users
      requestBody:
        description: "password must contain least one special char, lower and upper char, and a number"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/register"
            example:
              nickname: user1
              email: example@gmail.com
              password: UPlow123!
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/registerRes"
              example:
                _id: a1froas2314adf
                nickname: user1
        "400":
          description: "Bad Request, reason in body"

  /api/auth/logout:
    post:
      tags:
        - Auth
      description: test
      parameters: []
      responses:
        "200":
          description: OK
  /api/auth/token:
    post:
      tags:
        - Auth
      description: Get token
      parameters: []
      responses:
        "200":
          description: OK
  /api/users:
    get:
      tags:
        - User
      summary: ""
      description: ""
      parameters: []
      responses:
        "200":
          description: OK
  /api/:
    get:
      tags: []
      summary: ""
      description: ""
      parameters: []
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    register:
      required:
        - email
        - nickname
        - password
      properties:
        nickname:
          type: string
          minimum: 3
        email:
          type: string
          uniqueItems: true
        password:
          type: string
          minimum: 8
          maximum: 15
          description: "must contain least one special char, lower and upper char, and a number"
    registerRes:
      properties:
        _id:
          type: string
        nickname:
          type: string
    login:
      required:
        - email
        - password
      properties:
        email:
          type: string
          uniqueItems: true
        password:
          type: string
          minimum: 8
          maximum: 15
          description: "must contain least one special char, lower and upper char, and a number"
    user_id:
      properties:
        user_id:
          type: string
    User:
      required:
        - _id
        - nickname
      properties:
        _id:
          type: string
          uniqueItems: true
        email:
          type: string
          uniqueItems: true
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jjw2995/tsns1/1.0.0
